/**
 * api/analyze.js — Multi-agent matchup analysis using LangGraph.js
 *
 * Architecture:
 *   START
 *     └─► router node — validates teams, fans out via Send()
 *           ├─► efficiency_agent  (Torvik AdjEM/OE/DE/Barthag)
 *           ├─► form_agent        (last-10, streak, recent margins)
 *           ├─► matchup_agent     (H2H, common opponents, pace)
 *           └─► odds_agent        (DraftKings spread/ML, ESPN BPI, line movement, futures)
 *     └─► synthesis_node — weights all three, produces confidence interval
 *   END
 *
 * The three specialist agents run in parallel (LangGraph Send API).
 * Synthesis fires only after all three complete.
 *
 * Request:  POST { team_a: string, team_b: string }
 * Response: { agents: AgentResult[], confidence: ConfidenceResult, thinking: string[] }
 */

import { readFileSync }                              from 'fs';
import { join }                                      from 'path';
import { Annotation, StateGraph, END, START, Send } from '@langchain/langgraph';

// ── Constants ─────────────────────────────────────────────────────────────────
// ── Output sanitizer — strip CoT leakage before any LLM text reaches the client ──
// Removes: Note:/Explanation:/Reasoning: headers, <think> blocks, instruction echoes
function sanitizeLLMOutput(text) {
  if (!text) return text;
  const cleaned = text
    // Strip XML-style thinking blocks
    .replace(/<think>[\s\S]*?<\/think>/gi, '')
    // Strip "Note:" / "Disclaimer:" lines only
    .replace(/^(Note|Disclaimer|Reminder)[:\s][^\n]*/gim, '')
    // Collapse 3+ newlines to 2
    .replace(/\n{3,}/g, '\n\n')
    .trim();
  // If sanitizer wiped everything, return original trimmed text
  return cleaned || text.trim();
}

const GROQ_URL      = 'https://api.groq.com/openai/v1/chat/completions';
const MODEL         = 'llama-3.3-70b-versatile';
const MAX_TOKENS          = 1024;   // per specialist agent
const MAX_TOKENS_SYNTHESIS = 2048;  // synthesis needs room for depth
const FETCH_TIMEOUT = 20000;

const CORS = {
  'Access-Control-Allow-Origin':  '*',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type',
};

// ── Data loading ──────────────────────────────────────────────────────────────
let _cache = null;

function getData() {
  if (_cache) return _cache;
  const graph  = JSON.parse(readFileSync(join(process.cwd(), 'public', 'data', 'graph_data.json'),  'utf8'));
  const torvik = JSON.parse(readFileSync(join(process.cwd(), 'public', 'data', 'torvik_stats.json'), 'utf8'));
  const form   = JSON.parse(readFileSync(join(process.cwd(), 'public', 'data', 'recent_form.json'),  'utf8'));

  // Injury overrides — read-only, never written by this file
  let injuryMap = {};
  try {
    const raw = JSON.parse(readFileSync(join(process.cwd(), 'data', 'injury_overrides.json'), 'utf8'));
    for (const [espnId, override] of Object.entries(raw.overrides ?? {})) {
      const penalty = override.adj_em_penalty ?? 0;
      if (penalty <= 0) continue;
      injuryMap[espnId] = {
        penalty,
        players: override.players ?? [],
        notes:   override.notes ?? '',
        updated: override.updated ?? '',
      };
    }
  } catch {}

  const nodeByName = {};
  graph.nodes.forEach(n => {
    nodeByName[n.label.toLowerCase()]     = n;
    nodeByName[n.full_name.toLowerCase()] = n;
  });

  const edgesByNode = {};
  graph.edges.forEach(e => {
    (edgesByNode[e.from] = edgesByNode[e.from] || []).push(e);
    (edgesByNode[e.to]   = edgesByNode[e.to]   || []).push(e);
  });

  // Transitive path analysis — precomputed common-opponent chains
  let transPairs = {};
  try {
    const tp = JSON.parse(readFileSync(join(process.cwd(), 'data', 'transitive_analysis.json'), 'utf8'));
    transPairs = tp.pairs ?? {};
  } catch {}

  // ESPN odds + BPI data — generated by scripts/fetch_odds.py
  let oddsData = { games: {}, futures: {} };
  try {
    oddsData = JSON.parse(readFileSync(join(process.cwd(), 'public', 'data', 'espn_odds.json'), 'utf8'));
  } catch { /* file absent before first odds run — degrade gracefully */ }

  // Injury news keyed by ESPN team ID -> { bracket_name, articles[] }
  let injuryNews = {};
  try {
    const newsRaw = JSON.parse(readFileSync(join(process.cwd(), 'data', 'injury_news.json'), 'utf8'));
    injuryNews = newsRaw?.teams ?? {};
  } catch {}

  // Pre-fetched roster stats for all 76 bracket teams
  // Generated by scripts/fetch_rosters.py — keyed by ESPN team ID
  let rosterStats = {};
  try {
    rosterStats = JSON.parse(readFileSync(join(process.cwd(), 'data', 'roster_stats.json'), 'utf8')).teams ?? {};
  } catch {}

  _cache = { graph, torvik, form, injuryMap, transPairs, nodeByName, edgesByNode, oddsData, injuryNews, rosterStats };
  return _cache;
}

// ── Team resolution (same normalization as api/ai.js) ────────────────────────
function normalizeTeamName(s) {
  return s.toLowerCase().trim()
    .replace(/\bst\.\s*/g, 'saint ')
    .replace(/\bst\s+/g,   'saint ')
    .replace(/\bft\.?\s+/g, 'fort ')
    .replace(/[.'`]/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

const TEAM_ALIASES = {
  'unc': 'north carolina', 'uconn': 'uconn huskies', 'ucf': 'ucf knights',
  'ucla': 'ucla bruins',   'umbc': 'umbc retrievers', 'vcu': 'vcu rams',
  'tcu': 'tcu horned frogs', 'smu': 'smu mustangs',  'byu': 'byu cougars',
  'lsu': 'lsu tigers',     'ndsu': 'north dakota state', 'a&m': 'texas a&m',
  'liu': 'long island university', 'sam houston': 'sam houston bearkats',
};

function resolveTeam(name, nodeByName) {
  const raw      = name.toLowerCase().trim();
  const aliasKey = Object.keys(TEAM_ALIASES).find(k => raw === k || raw.startsWith(k + ' '));
  const queryStr = aliasKey ? TEAM_ALIASES[aliasKey] : normalizeTeamName(name);
  const normMap  = {};
  Object.keys(nodeByName).forEach(k => { normMap[normalizeTeamName(k)] = nodeByName[k]; });
  if (normMap[queryStr]) return normMap[queryStr];
  const candidates = Object.keys(normMap)
    .filter(k => k.includes(queryStr) || queryStr.includes(k))
    .sort((a, b) => {
      const aS = a.startsWith(queryStr) ? 1 : 0;
      const bS = b.startsWith(queryStr) ? 1 : 0;
      if (aS !== bS) return bS - aS;
      return b.length - a.length;
    });
  return candidates.length ? normMap[candidates[0]] : null;
}

// ── Data formatters ───────────────────────────────────────────────────────────
function fmtTeamFull(node, torvik, form, injuryMap) {
  const tv = torvik?.teams?.[node.id]?.torvik;
  const tf = form?.teams?.[node.id];
  if (!tv) return `${node.full_name}: no Torvik data`;

  const pace = tv.adj_tempo >= 0.7 ? 'fast' : tv.adj_tempo >= 0.4 ? 'moderate' : 'slow';
  const recent = tf?.games?.slice(-5).map(g =>
    `${g.date.slice(5)}: ${g.won ? 'W' : 'L'} ${g.score} vs ${g.opp}`
  ).join(', ') ?? 'no recent data';

  const inj = injuryMap?.[node.id];
  const injStr = inj
    ? `⚠ INJURY REPORT (model AdjEM penalty applied: -${inj.penalty}): ` +
      inj.players.map(p => `${p.name} — ${p.status}`).join('; ') +
      (inj.notes ? ` | ${inj.notes}` : '')
    : '';

  // Four Factors context
  const ffStr = tv ? [
    `eFG%: ${tv.efg ?? '?'} | TOV%: ${tv.tov_rate ?? '?'} | ORB%: ${tv.orb_rate ?? '?'} | FTR: ${tv.ftr ?? '?'}`,
    `Opp eFG%: ${tv.opp_efg ?? '?'} | Opp TOV%: ${tv.opp_tov ?? '?'}`,
  ].join(' | ') : '';

  return [
    `${node.full_name} (${node.region !== 'bubble' ? `${node.region} #${node.seed}` : 'bubble'}, ${tv.conf})`,
    `Record: ${tv.record} | vs bracket field: ${node.wins_vs_field}W-${node.losses_vs_field}L`,
    `T-Rank #${tv.rank} | AdjEM: ${tv.adj_em > 0 ? '+' : ''}${tv.adj_em} | AdjOE: ${tv.adj_oe} | AdjDE: ${tv.adj_de}`,
    `Barthag: ${(tv.barthag * 100).toFixed(1)}% | WAB: ${parseFloat(tv.wab).toFixed(1)} | SOS: ${tv.sos_rank?.toFixed(2) ?? '?'} | Pace: ${pace} (adj tempo: ${tv.adj_tempo?.toFixed(2) ?? '?'})`,
    `Shooting: 2P% ${tv.two_p} | 3P% ${tv.three_p} | FT% ${tv.ft_pct} | eFG% ${tv.efg}`,
    `Four Factors: ${ffStr}`,
    `Luck: ${tv.luck > 0 ? '+' : ''}${parseFloat(tv.luck ?? 0).toFixed(3)} (${tv.luck > 0.03 ? 'overperforming' : tv.luck < -0.03 ? 'underperforming' : 'neutral'})`,
    `Form: ${tf?.last10 ?? '?'} last 10 | Streak: ${tf?.streak ?? '?'}`,
    `Last 5: ${recent}`,
    injStr,
  ].filter(Boolean).join('\n');
}

// ── Groq fetch helper ─────────────────────────────────────────────────────────
async function groqCall(systemPrompt, userPrompt, groqKey, attempt = 0, maxTokens = MAX_TOKENS) {
  const ctrl  = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), FETCH_TIMEOUT);
  try {
    const res = await fetch(GROQ_URL, {
      method:  'POST',
      headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${groqKey}` },
      body: JSON.stringify({
        model:      MODEL,
        max_tokens: maxTokens,
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user',   content: userPrompt   },
        ],
      }),
      signal: ctrl.signal,
    });
    clearTimeout(timer);
    if (res.status === 429 && attempt < 2) {
      const wait = parseInt(res.headers.get('retry-after') || '5', 10);
      await new Promise(r => setTimeout(r, Math.min(wait, 10) * 1000));
      return groqCall(systemPrompt, userPrompt, groqKey, attempt + 1);
    }
    if (!res.ok) {
      const errBody = await res.json().catch(() => ({}));
      throw new Error(`Groq ${res.status}: ${errBody?.error?.message ?? 'unknown error'}`);
    }
    const data = await res.json();
    return data.choices?.[0]?.message?.content ?? '';
  } catch (err) {
    clearTimeout(timer);
    throw err;
  }
}

// ── LangGraph State definition ────────────────────────────────────────────────
// Each agent writes its result into agent_results (array, appended).
// Synthesis reads all results and writes final confidence.
const GraphState = Annotation.Root({
  team_a:        Annotation({ reducer: (_, b) => b }),
  team_b:        Annotation({ reducer: (_, b) => b }),
  team_a_data:   Annotation({ reducer: (_, b) => b }),
  team_b_data:   Annotation({ reducer: (_, b) => b }),
  matchup_data:  Annotation({ reducer: (_, b) => b }),
  odds_data:     Annotation({ reducer: (_, b) => b }),
  agent_results: Annotation({ reducer: (a, b) => [...(a ?? []), ...(Array.isArray(b) ? b : [b])] }),
  confidence:    Annotation({ reducer: (_, b) => b }),
  error:         Annotation({ reducer: (_, b) => b }),
});

// ── Node: router ──────────────────────────────────────────────────────────────
// Validates teams, enriches state with data. Returns plain object — NOT Send.
// Send/fan-out happens in routerEdge (the conditional edge function).

// ── Roster stats lookup (from pre-fetched roster_stats.json) ────────────────
// No live API calls — data is refreshed daily by scripts/fetch_rosters.py
function getRosterStats(teamId, rosterStats) {
  return rosterStats?.[String(teamId)]?.players ?? [];
}

// Format roster into a dense readable block for LLM agents
// Shows all players sorted by MPG with full individual stats
function fmtRoster(players) {
  if (!players?.length) return '';
  return players.map((p, i) => {
    const injNote  = p.injured ? ` ⚠ ${p.injured}` : '';
    const ageStr   = p.age ? `, age ${p.age}` : '';
    const identity = `${p.name} (${p.exp}${ageStr}, ${p.pos}, ${p.height}, ${p.weight})`;
    const usage    = `${p.mpg} MPG | ${p.gp} GP / ${p.gs} GS`;
    const scoring  = `${p.ppg}/${p.rpg}/${p.apg} pts/reb/ast`;
    const shooting = `FG ${p.fg}% | 3P ${p.three_pct}% | FT ${p.ft_pct}%`;
    const defense  = `STL ${p.spg} | BLK ${p.bpg} | TOV ${p.tov}`;
    const adv      = `PER ${p.per}`;
    return `  ${i + 1}. ${identity}${injNote}\n     ${usage} | ${scoring} | ${shooting} | ${defense} | ${adv}`;
  }).join('\n');
}

function routerNode(state) {
  const { graph, torvik, form, injuryMap, transPairs, nodeByName, edgesByNode, oddsData, injuryNews, rosterStats } = getData();
  const nodeA = resolveTeam(state.team_a, nodeByName);
  const nodeB = resolveTeam(state.team_b, nodeByName);

  if (!nodeA || !nodeB) {
    return { error: `Team not found: ${!nodeA ? state.team_a : state.team_b}` };
  }

  // Load pre-fetched roster stats from roster_stats.json (no live API calls)
  const rosterA    = getRosterStats(nodeA.id, rosterStats);
  const rosterB    = getRosterStats(nodeB.id, rosterStats);
  const rosterAStr = fmtRoster(rosterA);
  const rosterBStr = fmtRoster(rosterB);

  let teamAData = fmtTeamFull(nodeA, torvik, form, injuryMap);
  let teamBData = fmtTeamFull(nodeB, torvik, form, injuryMap);

  if (rosterAStr) teamAData += `\n\nROSTER (top 8 by minutes):\n${rosterAStr}`;
  if (rosterBStr) teamBData += `\n\nROSTER (top 8 by minutes):\n${rosterBStr}`;

  const aEdges = edgesByNode[nodeA.id] || [];
  const bEdges = edgesByNode[nodeB.id] || [];
  const h2h    = aEdges.filter(e =>
    (e.from === nodeA.id && e.to === nodeB.id) ||
    (e.from === nodeB.id && e.to === nodeA.id)
  );
  const aOpps = new Set(aEdges.map(e => e.from === nodeA.id ? e.to : e.from));
  const bOpps = new Set(bEdges.map(e => e.from === nodeB.id ? e.to : e.from));
  const common = [...aOpps].filter(id => bOpps.has(id)).slice(0, 6);

  const commonLines = common.map(cid => {
    const cNode = graph.nodes.find(n => n.id === cid);
    const aGame = aEdges.find(e => (e.from === nodeA.id && e.to === cid) || (e.to === nodeA.id && e.from === cid));
    const bGame = bEdges.find(e => (e.from === nodeB.id && e.to === cid) || (e.to === nodeB.id && e.from === cid));
    const aRes  = aGame ? (aGame.from === nodeA.id ? `W ${aGame.label} by ${aGame.margin}` : `L ${aGame.label} by ${aGame.margin}`) : '?';
    const bRes  = bGame ? (bGame.from === nodeB.id ? `W ${bGame.label} by ${bGame.margin}` : `L ${bGame.label} by ${bGame.margin}`) : '?';
    return `  vs ${cNode?.label ?? cid}: ${nodeA.label} ${aRes} | ${nodeB.label} ${bRes}`;
  });

  // Transitive path evidence from precomputed analysis
  const tKey  = `${nodeA.id}_${nodeB.id}`;
  const tKeyR = `${nodeB.id}_${nodeA.id}`;
  const tPair = transPairs[tKey] || transPairs[tKeyR];
  let transLines = '';
  if (tPair && tPair.n > 0) {
    const flipped = !!transPairs[tKeyR] && !transPairs[tKey];
    const favors  = tPair.verdict === 'a' ? (flipped ? nodeB.label : nodeA.label)
                  : tPair.verdict === 'b' ? (flipped ? nodeA.label : nodeB.label)
                  : 'neither';
    const chains  = [
      ...(tPair.a || []).slice(0, 2).map(s =>
        `  ${nodeA.label} beat ${s.common_name} (${s.a_score}), who beat ${nodeB.label} (${s.b_score})`),
      ...(tPair.b || []).slice(0, 2).map(s =>
        `  ${nodeB.label} beat ${s.common_name} (${s.b_score}), who beat ${nodeA.label} (${s.a_score})`),
    ];
    transLines = `Transitive evidence (${tPair.n} signals, conf ${tPair.conf?.toFixed(0) ?? '?'}/100, favors ${favors}):\n${chains.join('\n')}`;
  } else {
    transLines = 'Transitive evidence: none found in schedule data.';
  }

  const matchupData = [
    h2h.length
      ? `H2H: ${h2h.map(e => `${e.from === nodeA.id ? nodeA.label : nodeB.label} won ${e.label} by ${e.margin} on ${e.date}`).join(', ')}`
      : 'H2H: No head-to-head games this season.',
    common.length
      ? `Common bracket opponents (${common.length}):\n${commonLines.join('\n')}`
      : 'No common bracket opponents.',
    transLines,
  ].join('\n');

  // ── Build odds context from espn_odds.json ──────────────────────────────
  // Find the most recent tournament game featuring these two teams
  const oddsLines = [];
  const gamesArr  = Object.values(oddsData?.games ?? {});
  // Look for a game with both team IDs (home vs away)
  const matchGame = gamesArr.find(g =>
    (g.home_id === nodeA.id && g.away_id === nodeB.id) ||
    (g.home_id === nodeB.id && g.away_id === nodeA.id)
  );

  if (matchGame) {
    const isAHome = matchGame.home_id === nodeA.id;
    const odds    = matchGame.odds;
    const bpi     = matchGame.bpi;

    if (odds) {
      const aML    = isAHome ? odds.home_moneyline    : odds.away_moneyline;
      const bML    = isAHome ? odds.away_moneyline    : odds.home_moneyline;
      const aImp   = isAHome ? odds.home_implied_pct  : odds.away_implied_pct;
      const bImp   = isAHome ? odds.away_implied_pct  : odds.home_implied_pct;
      const openAML= isAHome ? odds.open_home_ml      : odds.open_away_ml;
      const mvmt   = odds.line_movement !== null && odds.line_movement !== undefined
        ? (isAHome ? odds.line_movement : -odds.line_movement)
        : null;

      oddsLines.push(`DraftKings (${odds.provider}):`);
      oddsLines.push(`  Spread: ${odds.spread >= 0 ? '+' : ''}${odds.spread} | O/U: ${odds.over_under}`);
      oddsLines.push(`  ${state.team_a} ML: ${aML} (${aImp}% implied) | ${state.team_b} ML: ${bML} (${bImp}% implied)`);
      if (openAML !== null && openAML !== undefined) {
        oddsLines.push(`  Opening ML for ${state.team_a}: ${openAML}${mvmt !== null ? ` → ${mvmt > 0 ? '+' : ''}${mvmt.toFixed(1)}% shift (${mvmt > 0 ? 'sharp money on ' + state.team_a : mvmt < 0 ? 'sharp money on ' + state.team_b : 'no movement'})` : ''}`);
      }
    }

    if (bpi) {
      const aBpi = isAHome ? bpi.home_bpi_win_pct : bpi.away_bpi_win_pct;
      const bBpi = isAHome ? bpi.away_bpi_win_pct : bpi.home_bpi_win_pct;
      oddsLines.push(`ESPN BPI (accounts for travel, rest, site, altitude):`);
      oddsLines.push(`  ${state.team_a}: ${aBpi}% | ${state.team_b}: ${bBpi}% | Pred margin: ${bpi.bpi_pred_margin > 0 ? '+' : ''}${bpi.bpi_pred_margin} | Matchup quality: ${bpi.matchup_quality}/100`);
    }
  } else {
    oddsLines.push('No tournament game odds found for this matchup yet.');
  }

  // Futures: championship and regional odds per team
  const futA = oddsData?.futures?.[state.team_a.toLowerCase()];
  const futB = oddsData?.futures?.[state.team_b.toLowerCase()];
  if (futA?.markets || futB?.markets) {
    oddsLines.push('Futures (DraftKings):');
    const fmtFut = (fut, name) => {
      if (!fut?.markets) return `  ${name}: no futures data`;
      const mkts = Object.entries(fut.markets)
        .map(([k, v]) => `${k.replace('region_', '').replace('_', ' ')}: ${v.moneyline} (${v.implied_pct}%)`)
        .join(' | ');
      return `  ${name}: ${mkts}`;
    };
    if (futA) oddsLines.push(fmtFut(futA, state.team_a));
    if (futB) oddsLines.push(fmtFut(futB, state.team_b));
  }

  const oddsContextStr = oddsLines.join('\n');

  // Append injury news narratives (keyed by ESPN team ID)
  const newsA = injuryNews?.[nodeA.id]?.articles;
  const newsB = injuryNews?.[nodeB.id]?.articles;
  const teamAFull = newsA?.length
    ? teamAData + `\nRecent injury news: ${newsA.slice(0,3).map(n => n.headline).join('; ')}`
    : teamAData;
  const teamBFull = newsB?.length
    ? teamBData + `\nRecent injury news: ${newsB.slice(0,3).map(n => n.headline).join('; ')}`
    : teamBData;

  return { team_a_data: teamAFull, team_b_data: teamBFull, matchup_data: matchupData, odds_data: oddsContextStr };
}

// ── Conditional edge function: routerEdge ─────────────────────────────────────
// LangGraph requires Send to come from the edge fn, not from the node itself.
// This fans out to 3 specialist agents in parallel.
function routerEdge(state) {
  if (state.error) return [END];
  return [
    new Send('efficiency_agent', state),
    new Send('form_agent',       state),
    new Send('matchup_agent',    state),
    new Send('odds_agent',       state),
  ];
}

// ── Node: efficiency_agent ────────────────────────────────────────────────────
// Uses Barthag (a literal head-to-head win probability) + AdjEM margin.
async function efficiencyAgent(state, config) {
  const groqKey = config.configurable?.groqKey;
  const system  = `You are an NCAA basketball efficiency analyst. Your job is to assess matchup probability using only efficiency metrics.
Respond with valid JSON only. No markdown, no explanation, no notes, no self-commentary outside the JSON object itself.
Schema: { "agent": "efficiency", "win_pct": <number 0-100 for ${state.team_a}>, "confidence": "low|medium|high", "key_edge": "<one specific stat advantage>", "reasoning": "<2-3 sentences citing exact numbers>" }`;

  const user = `Analyze this matchup using efficiency data only.

${state.team_a_data}

vs

${state.team_b_data}

Note: Barthag is a direct win probability estimate. An AdjEM gap >10 points is decisive, 5-10 is meaningful, <5 is a toss-up.
Return win probability for ${state.team_a}.`;

  try {
    const raw    = await groqCall(system, user, groqKey);
    const clean  = raw.replace(/```json|```/g, '').trim();
    const result = JSON.parse(clean);
    if (result.reasoning) result.reasoning = sanitizeLLMOutput(result.reasoning);
    return { agent_results: [result] };
  } catch (err) {
    console.error('[efficiency_agent] error:', err?.message ?? err);
    return { agent_results: [{ agent: 'efficiency', win_pct: 50, confidence: 'low', key_edge: 'parse error', reasoning: `Efficiency analysis error: ${err?.message ?? 'unknown'}` }] };
  }
}

// ── Node: form_agent ──────────────────────────────────────────────────────────
// Focuses on momentum: last-10, streak, recent scoring margins.
async function formAgent(state, config) {
  const groqKey = config.configurable?.groqKey;
  const system  = `You are an NCAA basketball momentum and form analyst. Assess matchup probability using only recent performance data.
Respond with valid JSON only. No markdown, no explanation, no notes, no self-commentary outside the JSON object itself.
Schema: { "agent": "form", "win_pct": <number 0-100 for ${state.team_a}>, "confidence": "low|medium|high", "key_edge": "<one specific form advantage>", "reasoning": "<2-3 sentences citing specific recent games or trends>" }`;

  const user = `Analyze this matchup using recent form data only.

${state.team_a_data}

vs

${state.team_b_data}

Focus on: last-10 W-L record, current win/loss streak, and scoring trends in the last 5 games.
Return win probability for ${state.team_a}.`;

  try {
    const raw    = await groqCall(system, user, groqKey);
    const clean  = raw.replace(/```json|```/g, '').trim();
    const result = JSON.parse(clean);
    if (result.reasoning) result.reasoning = sanitizeLLMOutput(result.reasoning);
    return { agent_results: [result] };
  } catch (err) {
    console.error('[form_agent] error:', err?.message ?? err);
    return { agent_results: [{ agent: 'form', win_pct: 50, confidence: 'low', key_edge: 'parse error', reasoning: `Form analysis error: ${err?.message ?? 'unknown'}` }] };
  }
}

// ── Node: matchup_agent ───────────────────────────────────────────────────────
// Focuses on H2H, common opponents, pace mismatch.
async function matchupAgent(state, config) {
  const groqKey = config.configurable?.groqKey;
  const system  = `You are an NCAA basketball matchup specialist. Assess win probability using head-to-head history and common opponent analysis.
Respond with valid JSON only. No markdown, no explanation, no notes, no self-commentary outside the JSON object itself.
Schema: { "agent": "matchup", "win_pct": <number 0-100 for ${state.team_a}>, "confidence": "low|medium|high", "key_edge": "<one specific matchup advantage>", "reasoning": "<2-3 sentences citing H2H or common opponent results>" }`;

  const user = `Analyze this matchup using head-to-head and common opponent data.

${state.team_a_data}

vs

${state.team_b_data}

Head-to-head and common opponent data:
${state.matchup_data}

Also consider pace mismatch: if one team plays fast and the other slow, the faster team usually dictates tempo.
Return win probability for ${state.team_a}.`;

  try {
    const raw    = await groqCall(system, user, groqKey);
    const clean  = raw.replace(/```json|```/g, '').trim();
    const result = JSON.parse(clean);
    if (result.reasoning) result.reasoning = sanitizeLLMOutput(result.reasoning);
    return { agent_results: [result] };
  } catch (err) {
    console.error('[matchup_agent] error:', err?.message ?? err);
    return { agent_results: [{ agent: 'matchup', win_pct: 50, confidence: 'low', key_edge: 'parse error', reasoning: `Matchup analysis error: ${err?.message ?? 'unknown'}` }] };
  }
}

// ── Node: odds_agent ──────────────────────────────────────────────────────────
// Interprets DraftKings spread/moneyline, BPI win probability, and line movement.
// No LLM call for the market-implied probability itself — math is math.
// LLM only synthesizes what the three signals collectively say.
async function oddsAgent(state, config) {
  const groqKey  = config.configurable?.groqKey;
  const oddsCtx  = state.odds_data ?? '';

  // If no odds data exists yet (pre-tournament, or file not generated), return neutral
  if (!oddsCtx || oddsCtx.includes('No tournament game odds found')) {
    return { agent_results: [{ agent: 'odds', win_pct: 50, confidence: 'low', key_edge: 'no market data', reasoning: 'No tournament betting lines available for this matchup yet.' }] };
  }

  const system = `You are a sports betting market analyst for NCAA basketball. Your job is to interpret betting market data and ESPN BPI predictions to assess win probability.
Respond with valid JSON only. No markdown, no explanation, no notes outside the JSON object.
Schema: { "agent": "odds", "win_pct": <number 0-100 for ${state.team_a}>, "confidence": "low|medium|high", "key_edge": "<one specific signal from the market or BPI>", "reasoning": "<2-3 sentences: cite the market-implied probability, BPI figure, and any meaningful line movement>" }`;

  const user = `Assess win probability for ${state.team_a} vs ${state.team_b} using market and BPI data.

${oddsCtx}

Rules for your analysis:
- Market-implied probability (from moneyline) is your baseline. It aggregates all available information.
- ESPN BPI is a second independent model that accounts for travel, rest, site, altitude. Give it significant weight.
- Line movement > 3% shift is meaningful (sharp money). Ignore movement < 2% as noise.
- If market and BPI agree within 5%, high confidence. If they disagree by >10%, note the conflict.
- Futures (regional/championship odds) are secondary context only — don't anchor to them.
Return win probability for ${state.team_a}.`;

  try {
    const raw    = await groqCall(system, user, groqKey);
    const clean  = raw.replace(/```json|```/g, '').trim();
    const result = JSON.parse(clean);
    if (result.reasoning) result.reasoning = sanitizeLLMOutput(result.reasoning);
    return { agent_results: [result] };
  } catch (err) {
    console.error('[odds_agent] error:', err?.message ?? err);
    return { agent_results: [{ agent: 'odds', win_pct: 50, confidence: 'low', key_edge: 'parse error', reasoning: `Odds analysis error: ${err?.message ?? 'unknown'}` }] };
  }
}

// ── Node: synthesis ───────────────────────────────────────────────────────────
// Weights: efficiency 40%, odds/BPI 20%, form 20%, matchup 20% (degrades if no market data).
// Produces final confidence interval and unified reasoning.
async function synthesisNode(state, config) {
  const groqKey = config.configurable?.groqKey;
  const results = state.agent_results ?? [];
  // Small delay so synthesis doesn't fire in the same second as the 4 parallel agents
  await new Promise(r => setTimeout(r, 1000));

  const effResult  = results.find(r => r.agent === 'efficiency') ?? { win_pct: 50, confidence: 'low', reasoning: '' };
  const formResult = results.find(r => r.agent === 'form')       ?? { win_pct: 50, confidence: 'low', reasoning: '' };
  const matchResult= results.find(r => r.agent === 'matchup')    ?? { win_pct: 50, confidence: 'low', reasoning: '' };
  const oddsResult = results.find(r => r.agent === 'odds')       ?? { win_pct: 50, confidence: 'low', key_edge: 'no market data', reasoning: '' };

  const safePct = (r) => {
    const n = Number(r.win_pct);
    if (isNaN(n)) return 50;
    return Math.max(1, Math.min(99, n));
  };

  // Odds agent weight drops to 0 if no market data available yet
  const oddsAvailable = !(oddsResult.confidence === 'low' && oddsResult.key_edge === 'no market data');
  const weights = oddsAvailable
    ? { efficiency: 0.40, odds: 0.20, form: 0.20, matchup: 0.20 }
    : { efficiency: 0.50, odds: 0.00, form: 0.25, matchup: 0.25 };

  const weightedPct = Math.round(
    (safePct(effResult)   * weights.efficiency) +
    (safePct(oddsResult)  * weights.odds)       +
    (safePct(formResult)  * weights.form)        +
    (safePct(matchResult) * weights.matchup)
  );

  const activePcts = oddsAvailable
    ? [safePct(effResult), safePct(formResult), safePct(matchResult), safePct(oddsResult)]
    : [safePct(effResult), safePct(formResult), safePct(matchResult)];
  const spread    = Math.max(...activePcts) - Math.min(...activePcts);
  const halfRange = Math.round(spread / 2 + 3);
  const rangeLow  = Math.max(1,  weightedPct - halfRange);
  const rangeHigh = Math.min(99, weightedPct + halfRange);

  const agentSummary = results.map(r =>
    `${r.agent.toUpperCase()} AGENT: ${r.win_pct}% for ${state.team_a} (${r.confidence} confidence)\nKey edge: ${r.key_edge}\n${r.reasoning}`
  ).join('\n\n');

  const weightDesc = oddsAvailable
    ? 'Efficiency 40%, Market/BPI 20%, Recent Form 20%, Matchup History 20%'
    : 'Efficiency 50%, Recent Form 25%, Matchup History 25% (no market data)';

  const system = `You are a senior NCAA tournament analyst. Write like The Athletic: deep, specific, opinionated. This is long-form expert analysis, not a summary.
You MUST respond with valid JSON only. No markdown fences, no backticks, no text outside the JSON object.
Schema:
{
  "injury_note": "<If ANY player has ⚠ in the roster data: 2-3 sentences on the injury, which player it is, their stats, and the direct impact on this specific matchup. If no injuries flagged, return empty string.>",
  "decisive_factor": "<4-6 sentences. The single biggest structural reason one team wins. Go deep: compare the specific efficiency metrics, explain the causal chain, cite the exact numbers from both rosters. Connect it to how the game will actually be played.>",
  "key_matchup": "<4-5 sentences. The player vs player or unit vs unit battle that decides the game. Name both players with their full stat lines — PPG, RPG, APG, FG%, experience year, height, weight. Explain the physical and stylistic mismatch. Cite who has the advantage and why.>",
  "x_factors": "<3-4 sentences. Two or three specific things — a player, a tendency, a situational factor — that most analysts are underweighting. Think: turnover rates, pace mismatch, rebounding margin, bench depth, specific shooting splits, Four Factors advantages. Cite numbers.>",
  "risk": "<3-4 sentences. The specific scenario where the favorite loses. Name the players involved, the game situation, the exact vulnerability. Make it concrete — not 'if they go cold' but 'if Cadeau (2.4 TOV/game) turns it over under pressure and Illinois converts in transition'.>",
  "market_vs_model": "<2-3 sentences. Compare the weighted model probability to the DraftKings implied probability and BPI. If they diverge by 6+ points, explain the gap and which signal to trust. If aligned, note what that consensus means for the prediction confidence.>",
  "bottom_line": "<2-3 sentences. Your firm prediction — who wins, why, by how much. Give a specific final score. Name the decisive player performance that seals it.>"
}`;

  const user = `Synthesize a deep expert matchup analysis. This should be as detailed and specific as a full pre-game scouting report.

TEAM DATA WITH FULL ROSTERS:
${state.team_a_data}

vs

${state.team_b_data}

AGENT REPORTS:
${agentSummary}

WEIGHTED WIN PROBABILITY for ${state.team_a}: ${weightedPct}% (range: ${rangeLow}-${rangeHigh}%)
Weights: ${weightDesc}
Agent spread: ${spread.toFixed(0)} pts (${spread < 10 ? 'strong consensus' : spread < 20 ? 'moderate agreement' : 'significant disagreement'})

RULES — follow these exactly:
- Every section must cite specific player names AND their stats from the roster data
- Every section must cite at least one efficiency number (AdjEM, AdjOE, AdjDE, eFG%, Barthag, TOV%, rebounding margin)
- injury_note: if any player has ⚠ in the roster, this must be non-empty and specific
- x_factors: go beyond the obvious — find the hidden edges that decide close games
- bottom_line: must include a specific score prediction like "Houston wins 74-69" and name the player who seals it
- Write like you are being paid to be right, not to be safe
Return only the JSON object. No backticks. No preamble.`;

  try {
    const raw   = await groqCall(system, user, groqKey, 0, MAX_TOKENS_SYNTHESIS);
    const clean = raw.replace(/```json|```/g, '').trim();

    let sections = {};
    try {
      sections = JSON.parse(clean);
    } catch {
      // Fallback: model didn't return valid JSON — use raw text as decisive_factor
      sections = { decisive_factor: sanitizeLLMOutput(clean) || results.map(r => r.reasoning).filter(Boolean).join(' ') };
    }

    // Sanitize each field
    const san = (s) => s ? sanitizeLLMOutput(String(s)) : '';

    // Build a flat reasoning string for backward compat (used by old chat path)
    const reasoning = [
      sections.decisive_factor,
      sections.key_matchup,
      sections.risk,
      sections.market_vs_model,
      sections.injury_note,
      sections.bottom_line,
    ].filter(Boolean).map(san).join('\n\n');

    const confidence = {
      team_a:       state.team_a,
      team_b:       state.team_b,
      win_pct:      weightedPct,
      range_low:    rangeLow,
      range_high:   rangeHigh,
      agent_spread: Math.round(spread),
      consensus:    spread < 10 ? 'strong' : spread < 20 ? 'moderate' : 'split',
      weights,
      reasoning,
      // Structured sections for rich UI rendering
      sections: {
        injury_note:      san(sections.injury_note      ?? ''),
        decisive_factor:  san(sections.decisive_factor  ?? ''),
        key_matchup:      san(sections.key_matchup      ?? ''),
        x_factors:        san(sections.x_factors        ?? ''),
        risk:             san(sections.risk              ?? ''),
        market_vs_model:  san(sections.market_vs_model  ?? ''),
        bottom_line:      san(sections.bottom_line      ?? ''),
      },
      agent_breakdown: results.map(r => ({
        agent:      r.agent,
        win_pct:    r.win_pct,
        confidence: r.confidence,
        key_edge:   r.key_edge,
      })),
    };
    return { confidence };
  } catch (err) {
    return { confidence: { error: err.message } };
  }
}

// ── Build LangGraph graph ─────────────────────────────────────────────────────
function buildGraph() {
  const workflow = new StateGraph(GraphState)
    .addNode('router',           routerNode)
    .addNode('efficiency_agent', efficiencyAgent)
    .addNode('form_agent',       formAgent)
    .addNode('matchup_agent',    matchupAgent)
    .addNode('odds_agent',       oddsAgent)
    .addNode('synthesis',        synthesisNode);

  // All four agents run in parallel, converge to synthesis
  workflow.addConditionalEdges('router', routerEdge);
  workflow.addEdge('efficiency_agent', 'synthesis');
  workflow.addEdge('form_agent',       'synthesis');
  workflow.addEdge('matchup_agent',    'synthesis');
  workflow.addEdge('odds_agent',       'synthesis');
  workflow.addEdge('synthesis',        END);
  workflow.addEdge(START, 'router');

  return workflow.compile();
}

const graph = buildGraph();

// ── Vercel handler ────────────────────────────────────────────────────────────
export default async function handler(req, res) {
  if (req.method === 'OPTIONS') {
    res.writeHead(204, CORS);
    res.end();
    return;
  }
  if (req.method !== 'POST') {
    res.writeHead(405, CORS);
    res.end(JSON.stringify({ error: 'Method not allowed' }));
    return;
  }

  let body;
  try {
    const raw = await new Promise((resolve, reject) => {
      let data = '';
      req.on('data', chunk => { data += chunk; });
      req.on('end',  () => resolve(data));
      req.on('error', reject);
    });
    body = JSON.parse(raw);
  } catch {
    res.writeHead(400, { 'Content-Type': 'application/json', ...CORS });
    res.end(JSON.stringify({ error: 'Invalid JSON' }));
    return;
  }

  const groqKey = process.env.GROQ_KEY_ANALYZE ?? process.env.GROQ_KEY;
  if (!groqKey) {
    res.writeHead(500, { 'Content-Type': 'application/json', ...CORS });
    res.end(JSON.stringify({ error: 'Server configuration error' }));
    return;
  }

  const { team_a, team_b } = body;
  if (!team_a || !team_b) {
    res.writeHead(400, { 'Content-Type': 'application/json', ...CORS });
    res.end(JSON.stringify({ error: 'team_a and team_b required' }));
    return;
  }
  if (typeof team_a !== 'string' || typeof team_b !== 'string' ||
      team_a.length > 200 || team_b.length > 200) {
    res.writeHead(400, { 'Content-Type': 'application/json', ...CORS });
    res.end(JSON.stringify({ error: 'Invalid team names' }));
    return;
  }

  try {
    const result = await graph.invoke(
      { team_a, team_b, agent_results: [] },
      { configurable: { groqKey } }
    );

    if (result.error) {
      res.writeHead(404, { 'Content-Type': 'application/json', ...CORS });
      res.end(JSON.stringify({ error: result.error }));
      return;
    }

    res.writeHead(200, { 'Content-Type': 'application/json', ...CORS });
    res.end(JSON.stringify({
      team_a,
      team_b,
      agent_results: result.agent_results,
      confidence:    result.confidence,
      odds_data:     result.odds_data ?? null,
    }));
  } catch (err) {
    res.writeHead(500, { 'Content-Type': 'application/json', ...CORS });
    res.end(JSON.stringify({ error: err.message }));
  }
}
